export const LOCATION_SELECTED = "LOCATION_SELECTED";
export const STORE_CATEGORY_LIST = "STORE_CATEGORY_LIST";
export const STORE_COMMERCIAL_CATEGORY_LIST = "STORE_COMMERCIAL_CATEGORY_LIST";
export const STORE_FILTER_DATA = "STORE_FILTER_DATA";
export const STORE_SLIDER_DISTANCE = "STORE_SLIDER_DISTANCE";
export const RESET_SLIDER_DISTANCE = "RESET_SLIDER_DISTANCE";
export const FETCH_CHAT_COUNTER = "FETCH_CHAT_COUNTER";
export const UPDATE_CHAT_COUNTER = "UPDATE_CHAT_COUNTER";